import os
import uuid
import cv2
import shutil
import tempfile

import torch


from app.modules.video.frame_extraction import extract_frames
from app.modules.video.extract_audio import extract_audio_from_video

from app.modules.video.gradcam import VideoGradCAM

from app.modules.video.face_helper import FaceHelper

from app.modules.audio.audio_preprocessing import extract_mel_spectrogram

from app.modules.video.lip_sync_model import extract_mouth_sequence

from app.modules.fusion.fusion_model import FusionModel


from app.config import (
    IMAGE_MODEL_PATH,
    VIDEO_MODEL_PATH,
    AUDIO_MODEL_PATH,
    LIPSYNC_MODEL_PATH,
    FUSION_MODEL_PATH
)



####################################################
# DEVICE
####################################################

DEVICE = torch.device(
    "cuda"
    if torch.cuda.is_available()
    else
    "cpu"
)





####################################################
# VIDEO DEEPFAKE SYSTEM
####################################################

class VideoDeepfakeSystem:



    def __init__(self):


        print(
            "\nLoading Fusion Detection System...\n"
        )



        ################################################
        # LOAD FUSION MODEL
        ################################################


        self.model = FusionModel(

            IMAGE_MODEL_PATH,

            VIDEO_MODEL_PATH,

            AUDIO_MODEL_PATH,

            LIPSYNC_MODEL_PATH

        )



        ################################################
        # LOAD FUSION WEIGHTS
        ################################################


        print(
            "Loading fusion checkpoint..."
        )


        checkpoint = torch.load(

            FUSION_MODEL_PATH,

            map_location=DEVICE

        )


        self.model.load_state_dict(

            checkpoint

        )


        print(
            "Fusion checkpoint loaded"
        )



        ################################################
        # DEVICE
        ################################################


        self.model.to(

            DEVICE

        )


        self.model.eval()



        ################################################
        # GRADCAM
        ################################################


        self.gradcam = VideoGradCAM(

            self.model.video_model

        )



        ################################################
        # FACE HELPER
        ################################################


        self.face_helper = FaceHelper(

            device=DEVICE

        )



        print(
            "\nFusion Detection System Ready\n"
        )





    ####################################################
    # FAKE PROBABILITY
    ####################################################


    def get_probability(

        self,

        logits

    ):


        probs = torch.softmax(

            logits,

            dim=1

        )


        return float(

            probs[:,1].item()

        )




    ####################################################
    # CONFIDENCE
    ####################################################


    def get_confidence(

        self,

        fake_probability

    ):


        if fake_probability >= 0.5:


            return fake_probability * 100


        else:


            return (1-fake_probability)*100


    ####################################################
    # EXPLANATION GENERATOR
    ####################################################

    def generate_explanation(

        self,

        prediction,

        metrics

    ):


        if prediction == "FAKE":


            return f"""

DeepGuardX detected possible deepfake manipulation.

AI forensic analysis:

Visual facial analysis:
{metrics.get("Image Analysis",0)}%

Video temporal analysis:
{metrics.get("Video Temporal Analysis",0)}%

Audio authenticity:
{metrics.get("Audio Analysis",0)}%

Lip synchronization:
{metrics.get("Lip Sync Analysis",0)}%

Fusion Transformer decision:
{metrics.get("Fusion Decision",0)}%

The final decision is generated by combining all modalities using the multimodal fusion network.

"""



        else:


            return f"""

DeepGuardX detected authentic media.

AI forensic analysis:

Visual facial analysis:
{metrics.get("Image Analysis",0)}%

Video temporal analysis:
{metrics.get("Video Temporal Analysis",0)}%

Audio authenticity:
{metrics.get("Audio Analysis",0)}%

Lip synchronization:
{metrics.get("Lip Sync Analysis",0)}%

Fusion Transformer decision:
{metrics.get("Fusion Decision",0)}%

All analyzed modalities show consistent patterns.

"""





    ####################################################
    # PREDICT
    ####################################################

    def predict(

        self,

        video_path

    ):


        print(

            "\nProcessing:",

            video_path

        )



        ################################################
        # FRAME EXTRACTION
        ################################################


        frames_dir = extract_frames(

            video_path,

            max_frames=16

        )



        audio_file = tempfile.mktemp(

            suffix=".wav"

        )



        try:



            ################################################
            # PROCESS FRAMES
            ################################################


            frame_tensors = []

            original_frames = []



            files = sorted(

                os.listdir(frames_dir)

            )



            for file in files:


                frame_path = os.path.join(

                    frames_dir,

                    file

                )



                frame = cv2.imread(

                    frame_path

                )



                if frame is None:

                    continue



                original_frames.append(

                    frame

                )



                face = self.face_helper.process_frame(

                    frame

                )



                if face is not None:


                    frame_tensors.append(

                        face.cpu()

                    )





            if len(frame_tensors)==0:


                raise Exception(

                    "No face detected"

                )





            ################################################
            # FIX 16 FRAMES
            ################################################


            while len(frame_tensors)<16:


                frame_tensors.append(

                    frame_tensors[-1].clone()

                )



            frame_tensors = frame_tensors[:16]




            while len(original_frames)<16:


                original_frames.append(

                    original_frames[-1].copy()

                )



            original_frames = original_frames[:16]






            ################################################
            # IMAGE INPUT
            ################################################


            image_input = frame_tensors[0].unsqueeze(0)



            image_input = image_input.to(

                DEVICE

            )






            ################################################
            # VIDEO INPUT
            ################################################


            video_input = torch.stack(

                frame_tensors

            ).unsqueeze(0)



            video_input = video_input.to(

                DEVICE

            )






            ################################################
            # AUDIO INPUT
            ################################################


            audio_path = extract_audio_from_video(

                video_path,

                audio_file

            )



            if audio_path:


                mel = extract_mel_spectrogram(

                    audio_path,

                    augment=False

                )



                if mel.dim()==2:

                    mel = mel.unsqueeze(0)



                audio_input = mel.unsqueeze(0)



                audio_input = audio_input.to(

                    DEVICE

                )


            else:


                audio_input = torch.zeros(

                    1,
                    1,
                    128,
                    95

                ).to(

                    DEVICE

                )






            ################################################
            # LIP INPUT
            ################################################


            lip_input = extract_mouth_sequence(

                frames_dir,

                target_frames=20

            )



            if lip_input is None:


                raise Exception(

                    "Lip extraction failed"

                )



            lip_input = lip_input.to(

                DEVICE

            )





            ################################################
            # SHAPE DEBUG
            ################################################


            print("\n==============================")

            print("INFERENCE INPUT SHAPES")

            print("==============================")


            print(
                "Image:",
                image_input.shape
            )


            print(
                "Video:",
                video_input.shape
            )


            print(
                "Audio:",
                audio_input.shape
            )


            print(
                "Lip:",
                lip_input.shape
            )


            print("==============================")





            ################################################
            # FUSION PREDICTION
            ################################################


            with torch.no_grad():


                logits = self.model(

                    image_input,

                    video_input,

                    audio_input,

                    lip_input

                )



                probabilities = torch.softmax(

                    logits,

                    dim=1

                )



                fake_probability = self.get_probability(

                    logits

                )



            print(

                "\nFusion Output:"

            )

            print(

                probabilities

            )




            ################################################
            # FINAL LABEL
            ################################################


            prediction = (

                "FAKE"

                if fake_probability >=0.5

                else

                "REAL"

            )



            confidence = self.get_confidence(

                fake_probability

            )


            ################################################
            # AI FORENSIC METRICS
            ################################################


            metrics = {}


            try:


                ########################################
                # IMAGE SCORE
                ########################################


                image_logits = self.model.image_model(

                    image_input

                )


                image_fake = torch.softmax(

                    image_logits,

                    dim=1

                )[0][1].item()



                metrics["Image Analysis"] = round(

                    image_fake * 100,

                    2

                )




                ########################################
                # VIDEO SCORE
                ########################################


                _, video_logits, _ = self.model.video_model(

                    video_input,

                    return_features=True

                )



                video_fake = torch.softmax(

                    video_logits,

                    dim=1

                )[0][1].item()



                metrics["Video Temporal Analysis"] = round(

                    video_fake * 100,

                    2

                )





                ########################################
                # AUDIO SCORE
                ########################################


                audio_logits = self.model.audio_model(

                    audio_input

                )



                audio_fake = torch.softmax(

                    audio_logits,

                    dim=1

                )[0][1].item()



                metrics["Audio Analysis"] = round(

                    audio_fake * 100,

                    2

                )





                ########################################
                # LIP SYNC SCORE
                ########################################


                _, lip_logits = self.model.lip_model(

                    lip_input,

                    return_features=True

                )



                lip_fake = torch.softmax(

                    lip_logits,

                    dim=1

                )[0][1].item()



                metrics["Lip Sync Analysis"] = round(

                    lip_fake * 100,

                    2

                )



            except Exception as e:


                print(

                    "Metric error:",

                    e

                )





            ########################################
            # FUSION SCORE
            ########################################


            metrics["Fusion Decision"] = round(

                fake_probability * 100,

                2

            )



            print(

                "\nAI FORENSIC METRICS"

            )

            print(

                metrics

            )





            ################################################
            # EXPLANATION
            ################################################


            explanation = self.generate_explanation(

                prediction,

                metrics

            )





            ################################################
            # VIDEO GRADCAM
            # ONLY TOP 5 IMAGES RETURNED
            ################################################


            gradcam_images = []



            ################################################
            # GRADCAM GENERATION
            ################################################

            try:

                print("\nGenerating GradCAM...")


                cam = self.gradcam.generate(
                    video_input
                )


                top_frames = self.gradcam.suspicious_frames(
                    cam,
                    top_k=5
                )


                # UNIQUE DIRECTORY FOR EACH VIDEO
                gradcam_id = str(uuid.uuid4())[:8]


                gradcam_folder = os.path.join(
                    "static",
                    "gradcam",
                    gradcam_id
                )


                os.makedirs(
                    gradcam_folder,
                    exist_ok=True
                )


                gradcam_images = self.gradcam.save_heatmaps(

                    [cam[i["frame"]-1] for i in top_frames],

                    [original_frames[i["frame"]-1] for i in top_frames],

                    gradcam_folder

                )


                # convert to frontend URLs

                gradcam_images = [

                    path.replace("\\","/")

                    for path in gradcam_images

                ]


                print(
                    "New GradCAM folder:",
                    gradcam_folder
                )


            except Exception as e:

                print(
                    "GradCAM failed:",
                    e
                )








            ################################################
            # FINAL RETURN
            ################################################


            return {


                "prediction":

                prediction,



                "confidence":

                round(

                    confidence,

                    2

                ),



                "explanation":

                explanation,



                "metrics":

                metrics,



                "gradcam_images":

                gradcam_images


            }





        finally:



            ################################################
            # CLEANUP
            ################################################


            shutil.rmtree(

                frames_dir,

                ignore_errors=True

            )



            if os.path.exists(audio_file):


                try:


                    os.remove(

                        audio_file

                    )


                except Exception:


                    pass